version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NLog.Extensions.Logging
    versions:
    - 1.7.0
    - 1.7.1
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: Microsoft.Extensions.Configuration.FileExtensions
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration.Json
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Logging
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration.EnvironmentVariables
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration.Binder
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - 5.0.0
