language: csharp
mono: none
dotnet: 3.1
dist: bionic
script:
 - cd JN.RabbitMQClient
 - dotnet restore
 - dotnet build --configuration Release --no-restore --framework netstandard2.0
 - cd ..
 - cd JN.RabbitMQClient.Tests
 - dotnet test
